#ifndef PARAMETERS_H
#define PARAMETERS_H
#include "Arduino.h"

#define NB_SONARS 5

#define SONAR_ECHO_FRONT_L SONAR_0_ECHO
#define SONAR_TRIG_FRONT_L SONAR_0_TRIG
#define SONAR_ECHO_FRONT_R SONAR_1_ECHO
#define SONAR_TRIG_FRONT_R SONAR_1_TRIG
#define SONAR_ECHO_R       SONAR_2_ECHO
#define SONAR_TRIG_R       SONAR_2_TRIG
#define SONAR_ECHO_L       SONAR_3_ECHO
#define SONAR_TRIG_L       SONAR_3_TRIG
#define SONAR_ECHO_BACK    SONAR_4_ECHO
#define SONAR_TRIG_BACK    SONAR_4_TRIG

//#define SONAR_ECHO_R       SONAR_5_ECHO
//#define SONAR_TRIG_R       SONAR_5_TRIG

#endif
